// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET acked_at = coalesce(acked_at, $1), ack_note = coalesce(ack_note, $2), updated_at = now()
WHERE id = $3
RETURNING id, device_id, home_id, code, severity, raised_at, last_seen_at, occurrences, acked_at, ack_note, resolved_at, resolve_reason, message, source, trigger_key, notify_state, notify_attempts, notified_at, resolve_notify_state, resolve_notify_attempts, updated_at, inserted_at
`

type AcknowledgeAlertParams struct {
	AckedAt sql.NullTime
	Note    pgtype.Text
	ID      uuid.UUID
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.AckedAt, arg.Note, arg.ID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.HomeID,
		&i.Code,
		&i.Severity,
		&i.RaisedAt,
		&i.LastSeenAt,
		&i.Occurrences,
		&i.AckedAt,
		&i.AckNote,
		&i.ResolvedAt,
		&i.ResolveReason,
		&i.Message,
		&i.Source,
		&i.TriggerKey,
		&i.NotifyState,
		&i.NotifyAttempts,
		&i.NotifiedAt,
		&i.ResolveNotifyState,
		&i.ResolveNotifyAttempts,
		&i.UpdatedAt,
		&i.InsertedAt,
	)
	return i, err
}

const countOpenAlertsByCode = `-- name: CountOpenAlertsByCode :many
SELECT code, count(*)::bigint AS n FROM alerts WHERE resolved_at IS NULL GROUP BY code ORDER BY code
`

type CountOpenAlertsByCodeRow struct {
	Code int16
	N    int64
}

func (q *Queries) CountOpenAlertsByCode(ctx context.Context) ([]CountOpenAlertsByCodeRow, error) {
	rows, err := q.db.Query(ctx, countOpenAlertsByCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenAlertsByCodeRow{}
	for rows.Next() {
		var i CountOpenAlertsByCodeRow
		if err := rows.Scan(&i.Code, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlert = `-- name: GetAlert :one
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a LEFT JOIN homes h ON h.id = a.home_id
WHERE a.id = $1
`

type GetAlertRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.Alert.ID,
		&i.Alert.DeviceID,
		&i.Alert.HomeID,
		&i.Alert.Code,
		&i.Alert.Severity,
		&i.Alert.RaisedAt,
		&i.Alert.LastSeenAt,
		&i.Alert.Occurrences,
		&i.Alert.AckedAt,
		&i.Alert.AckNote,
		&i.Alert.ResolvedAt,
		&i.Alert.ResolveReason,
		&i.Alert.Message,
		&i.Alert.Source,
		&i.Alert.TriggerKey,
		&i.Alert.NotifyState,
		&i.Alert.NotifyAttempts,
		&i.Alert.NotifiedAt,
		&i.Alert.ResolveNotifyState,
		&i.Alert.ResolveNotifyAttempts,
		&i.Alert.UpdatedAt,
		&i.Alert.InsertedAt,
		&i.SegmentID,
	)
	return i, err
}

const getOpenAlert = `-- name: GetOpenAlert :one

SELECT id, device_id, home_id, code, severity, raised_at, last_seen_at, occurrences, acked_at, ack_note, resolved_at, resolve_reason, message, source, trigger_key, notify_state, notify_attempts, notified_at, resolve_notify_state, resolve_notify_attempts, updated_at, inserted_at FROM alerts WHERE device_id = $1 AND code = $2 AND resolved_at IS NULL
`

type GetOpenAlertParams struct {
	DeviceID string
	Code     int16
}

// The alerts service is the single writer of this table.
func (q *Queries) GetOpenAlert(ctx context.Context, arg GetOpenAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlert, arg.DeviceID, arg.Code)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.HomeID,
		&i.Code,
		&i.Severity,
		&i.RaisedAt,
		&i.LastSeenAt,
		&i.Occurrences,
		&i.AckedAt,
		&i.AckNote,
		&i.ResolvedAt,
		&i.ResolveReason,
		&i.Message,
		&i.Source,
		&i.TriggerKey,
		&i.NotifyState,
		&i.NotifyAttempts,
		&i.NotifiedAt,
		&i.ResolveNotifyState,
		&i.ResolveNotifyAttempts,
		&i.UpdatedAt,
		&i.InsertedAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :one
INSERT INTO alerts (device_id, home_id, code, severity, raised_at, last_seen_at, message, source, trigger_key, notify_state)
VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9)
RETURNING id, device_id, home_id, code, severity, raised_at, last_seen_at, occurrences, acked_at, ack_note, resolved_at, resolve_reason, message, source, trigger_key, notify_state, notify_attempts, notified_at, resolve_notify_state, resolve_notify_attempts, updated_at, inserted_at
`

type InsertAlertParams struct {
	DeviceID    string
	HomeID      uuid.NullUUID
	Code        int16
	Severity    int16
	RaisedAt    time.Time
	Message     string
	Source      string
	TriggerKey  string
	NotifyState string
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, insertAlert,
		arg.DeviceID,
		arg.HomeID,
		arg.Code,
		arg.Severity,
		arg.RaisedAt,
		arg.Message,
		arg.Source,
		arg.TriggerKey,
		arg.NotifyState,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.HomeID,
		&i.Code,
		&i.Severity,
		&i.RaisedAt,
		&i.LastSeenAt,
		&i.Occurrences,
		&i.AckedAt,
		&i.AckNote,
		&i.ResolvedAt,
		&i.ResolveReason,
		&i.Message,
		&i.Source,
		&i.TriggerKey,
		&i.NotifyState,
		&i.NotifyAttempts,
		&i.NotifiedAt,
		&i.ResolveNotifyState,
		&i.ResolveNotifyAttempts,
		&i.UpdatedAt,
		&i.InsertedAt,
	)
	return i, err
}

const lastNotifiedAt = `-- name: LastNotifiedAt :one
SELECT notified_at FROM alerts
WHERE device_id = $1 AND code = $2 AND notify_state = 'sent' AND notified_at IS NOT NULL
ORDER BY notified_at DESC LIMIT 1
`

type LastNotifiedAtParams struct {
	DeviceID string
	Code     int16
}

// Most recent successful raise notification for (device, code); no row = never.
func (q *Queries) LastNotifiedAt(ctx context.Context, arg LastNotifiedAtParams) (sql.NullTime, error) {
	row := q.db.QueryRow(ctx, lastNotifiedAt, arg.DeviceID, arg.Code)
	var notified_at sql.NullTime
	err := row.Scan(&notified_at)
	return notified_at, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a LEFT JOIN homes h ON h.id = a.home_id
WHERE a.resolved_at IS NULL
  AND ($1::uuid IS NULL OR a.home_id = $1)
  AND ($2::text IS NULL OR h.segment_id = $2)
ORDER BY a.raised_at DESC
`

type ListActiveAlertsParams struct {
	HomeID    uuid.NullUUID
	SegmentID pgtype.Text
}

type ListActiveAlertsRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

func (q *Queries) ListActiveAlerts(ctx context.Context, arg ListActiveAlertsParams) ([]ListActiveAlertsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlerts, arg.HomeID, arg.SegmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertsRow{}
	for rows.Next() {
		var i ListActiveAlertsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.DeviceID,
			&i.Alert.HomeID,
			&i.Alert.Code,
			&i.Alert.Severity,
			&i.Alert.RaisedAt,
			&i.Alert.LastSeenAt,
			&i.Alert.Occurrences,
			&i.Alert.AckedAt,
			&i.Alert.AckNote,
			&i.Alert.ResolvedAt,
			&i.Alert.ResolveReason,
			&i.Alert.Message,
			&i.Alert.Source,
			&i.Alert.TriggerKey,
			&i.Alert.NotifyState,
			&i.Alert.NotifyAttempts,
			&i.Alert.NotifiedAt,
			&i.Alert.ResolveNotifyState,
			&i.Alert.ResolveNotifyAttempts,
			&i.Alert.UpdatedAt,
			&i.Alert.InsertedAt,
			&i.SegmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsForDevice = `-- name: ListAlertsForDevice :many
SELECT id, device_id, home_id, code, severity, raised_at, last_seen_at, occurrences, acked_at, ack_note, resolved_at, resolve_reason, message, source, trigger_key, notify_state, notify_attempts, notified_at, resolve_notify_state, resolve_notify_attempts, updated_at, inserted_at FROM alerts WHERE device_id = $1 ORDER BY raised_at, code
`

func (q *Queries) ListAlertsForDevice(ctx context.Context, deviceID string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.HomeID,
			&i.Code,
			&i.Severity,
			&i.RaisedAt,
			&i.LastSeenAt,
			&i.Occurrences,
			&i.AckedAt,
			&i.AckNote,
			&i.ResolvedAt,
			&i.ResolveReason,
			&i.Message,
			&i.Source,
			&i.TriggerKey,
			&i.NotifyState,
			&i.NotifyAttempts,
			&i.NotifiedAt,
			&i.ResolveNotifyState,
			&i.ResolveNotifyAttempts,
			&i.UpdatedAt,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRaiseNotifications = `-- name: ListPendingRaiseNotifications :many
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a LEFT JOIN homes h ON h.id = a.home_id
WHERE (a.notify_state = 'pending')
   OR (a.notify_state = 'failed' AND a.notify_attempts < $1
       AND a.updated_at < now() - make_interval(secs => $2::float8))
ORDER BY a.raised_at
LIMIT $3
`

type ListPendingRaiseNotificationsParams struct {
	MaxAttempts  int32
	RetrySeconds float64
	Lim          int32
}

type ListPendingRaiseNotificationsRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

func (q *Queries) ListPendingRaiseNotifications(ctx context.Context, arg ListPendingRaiseNotificationsParams) ([]ListPendingRaiseNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRaiseNotifications, arg.MaxAttempts, arg.RetrySeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRaiseNotificationsRow{}
	for rows.Next() {
		var i ListPendingRaiseNotificationsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.DeviceID,
			&i.Alert.HomeID,
			&i.Alert.Code,
			&i.Alert.Severity,
			&i.Alert.RaisedAt,
			&i.Alert.LastSeenAt,
			&i.Alert.Occurrences,
			&i.Alert.AckedAt,
			&i.Alert.AckNote,
			&i.Alert.ResolvedAt,
			&i.Alert.ResolveReason,
			&i.Alert.Message,
			&i.Alert.Source,
			&i.Alert.TriggerKey,
			&i.Alert.NotifyState,
			&i.Alert.NotifyAttempts,
			&i.Alert.NotifiedAt,
			&i.Alert.ResolveNotifyState,
			&i.Alert.ResolveNotifyAttempts,
			&i.Alert.UpdatedAt,
			&i.Alert.InsertedAt,
			&i.SegmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingResolveNotifications = `-- name: ListPendingResolveNotifications :many
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a LEFT JOIN homes h ON h.id = a.home_id
WHERE (a.resolve_notify_state = 'pending')
   OR (a.resolve_notify_state = 'failed' AND a.resolve_notify_attempts < $1
       AND a.updated_at < now() - make_interval(secs => $2::float8))
ORDER BY a.resolved_at
LIMIT $3
`

type ListPendingResolveNotificationsParams struct {
	MaxAttempts  int32
	RetrySeconds float64
	Lim          int32
}

type ListPendingResolveNotificationsRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

func (q *Queries) ListPendingResolveNotifications(ctx context.Context, arg ListPendingResolveNotificationsParams) ([]ListPendingResolveNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingResolveNotifications, arg.MaxAttempts, arg.RetrySeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingResolveNotificationsRow{}
	for rows.Next() {
		var i ListPendingResolveNotificationsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.DeviceID,
			&i.Alert.HomeID,
			&i.Alert.Code,
			&i.Alert.Severity,
			&i.Alert.RaisedAt,
			&i.Alert.LastSeenAt,
			&i.Alert.Occurrences,
			&i.Alert.AckedAt,
			&i.Alert.AckNote,
			&i.Alert.ResolvedAt,
			&i.Alert.ResolveReason,
			&i.Alert.Message,
			&i.Alert.Source,
			&i.Alert.TriggerKey,
			&i.Alert.NotifyState,
			&i.Alert.NotifyAttempts,
			&i.Alert.NotifiedAt,
			&i.Alert.ResolveNotifyState,
			&i.Alert.ResolveNotifyAttempts,
			&i.Alert.UpdatedAt,
			&i.Alert.InsertedAt,
			&i.SegmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDevices = `-- name: ListStaleDevices :many
SELECT dev_eui, home_id, last_seen_at
FROM devices
WHERE kind = 'house' AND last_seen_at IS NOT NULL
  AND last_seen_at < now() - make_interval(secs => $1::float8)
`

type ListStaleDevicesRow struct {
	DevEui     string
	HomeID     uuid.NullUUID
	LastSeenAt sql.NullTime
}

// Devices silent longer than the given number of seconds (wall clock).
func (q *Queries) ListStaleDevices(ctx context.Context, afterSeconds float64) ([]ListStaleDevicesRow, error) {
	rows, err := q.db.Query(ctx, listStaleDevices, afterSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleDevicesRow{}
	for rows.Next() {
		var i ListStaleDevicesRow
		if err := rows.Scan(&i.DevEui, &i.HomeID, &i.LastSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRaiseNotification = `-- name: MarkRaiseNotification :exec
UPDATE alerts
SET notify_state = $1,
    notified_at = CASE WHEN $1::text = 'sent' THEN now() ELSE notified_at END,
    notify_attempts = notify_attempts + 1,
    updated_at = now()
WHERE id = $2
`

type MarkRaiseNotificationParams struct {
	State string
	ID    uuid.UUID
}

func (q *Queries) MarkRaiseNotification(ctx context.Context, arg MarkRaiseNotificationParams) error {
	_, err := q.db.Exec(ctx, markRaiseNotification, arg.State, arg.ID)
	return err
}

const markResolveNotification = `-- name: MarkResolveNotification :exec
UPDATE alerts
SET resolve_notify_state = $1,
    resolve_notify_attempts = resolve_notify_attempts + 1,
    updated_at = now()
WHERE id = $2
`

type MarkResolveNotificationParams struct {
	State string
	ID    uuid.UUID
}

func (q *Queries) MarkResolveNotification(ctx context.Context, arg MarkResolveNotificationParams) error {
	_, err := q.db.Exec(ctx, markResolveNotification, arg.State, arg.ID)
	return err
}

const resolveOpenAlert = `-- name: ResolveOpenAlert :one
UPDATE alerts
SET resolved_at = $1, resolve_reason = $2,
    resolve_notify_state = CASE WHEN $3::boolean AND notify_state IN ('sent', 'pending') THEN 'pending' ELSE 'none' END,
    updated_at = now()
WHERE device_id = $4 AND code = $5 AND resolved_at IS NULL
  AND raised_at <= $1 -- a stale row from a lagging source cannot resolve a newer episode
RETURNING id, device_id, home_id, code, severity, raised_at, last_seen_at, occurrences, acked_at, ack_note, resolved_at, resolve_reason, message, source, trigger_key, notify_state, notify_attempts, notified_at, resolve_notify_state, resolve_notify_attempts, updated_at, inserted_at
`

type ResolveOpenAlertParams struct {
	ResolvedAt    sql.NullTime
	ResolveReason pgtype.Text
	NotifyResolve bool
	DeviceID      string
	Code          int16
}

func (q *Queries) ResolveOpenAlert(ctx context.Context, arg ResolveOpenAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveOpenAlert,
		arg.ResolvedAt,
		arg.ResolveReason,
		arg.NotifyResolve,
		arg.DeviceID,
		arg.Code,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.HomeID,
		&i.Code,
		&i.Severity,
		&i.RaisedAt,
		&i.LastSeenAt,
		&i.Occurrences,
		&i.AckedAt,
		&i.AckNote,
		&i.ResolvedAt,
		&i.ResolveReason,
		&i.Message,
		&i.Source,
		&i.TriggerKey,
		&i.NotifyState,
		&i.NotifyAttempts,
		&i.NotifiedAt,
		&i.ResolveNotifyState,
		&i.ResolveNotifyAttempts,
		&i.UpdatedAt,
		&i.InsertedAt,
	)
	return i, err
}

const touchAlert = `-- name: TouchAlert :exec
UPDATE alerts
SET raised_at = LEAST(raised_at, $1), last_seen_at = GREATEST(last_seen_at, $1),
    occurrences = occurrences + 1, updated_at = now()
WHERE id = $2
`

type TouchAlertParams struct {
	SeenAt time.Time
	ID     uuid.UUID
}

// Sources are consumed at different watermark positions, so the same episode
// can be observed out of event-time order: raised_at is the earliest trigger.
func (q *Queries) TouchAlert(ctx context.Context, arg TouchAlertParams) error {
	_, err := q.db.Exec(ctx, touchAlert, arg.SeenAt, arg.ID)
	return err
}
