// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const setCycleVolume = `-- name: SetCycleVolume :batchexec
UPDATE cycle_events SET est_volume_l = $1
WHERE device_id = $2 AND started_at = $3 AND f_cnt = $4
`

type SetCycleVolumeBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SetCycleVolumeParams struct {
	EstVolumeL pgtype.Float4
	DeviceID   string
	StartedAt  time.Time
	FCnt       int64
}

func (q *Queries) SetCycleVolume(ctx context.Context, arg []SetCycleVolumeParams) *SetCycleVolumeBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EstVolumeL,
			a.DeviceID,
			a.StartedAt,
			a.FCnt,
		}
		batch.Queue(setCycleVolume, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SetCycleVolumeBatchResults{br, len(arg), false}
}

func (b *SetCycleVolumeBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SetCycleVolumeBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
