// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detector.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDevicePitArea = `-- name: GetDevicePitArea :one
SELECT d.dev_eui, d.home_id, h.pit_area_m2::float8 AS pit_area_m2, h.segment_id
FROM devices d
LEFT JOIN homes h ON h.id = d.home_id
WHERE d.dev_eui = $1
`

type GetDevicePitAreaRow struct {
	DevEui    string
	HomeID    uuid.NullUUID
	PitAreaM2 float64
	SegmentID pgtype.Text
}

func (q *Queries) GetDevicePitArea(ctx context.Context, devEui string) (GetDevicePitAreaRow, error) {
	row := q.db.QueryRow(ctx, getDevicePitArea, devEui)
	var i GetDevicePitAreaRow
	err := row.Scan(
		&i.DevEui,
		&i.HomeID,
		&i.PitAreaM2,
		&i.SegmentID,
	)
	return i, err
}

const insertDetection = `-- name: InsertDetection :execrows
INSERT INTO detections (device_id, code, action, observed_at, f_cnt, detail)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type InsertDetectionParams struct {
	DeviceID   string
	Code       int16
	Action     int16
	ObservedAt time.Time
	FCnt       int64
	Detail     []byte
}

func (q *Queries) InsertDetection(ctx context.Context, arg InsertDetectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDetection,
		arg.DeviceID,
		arg.Code,
		arg.Action,
		arg.ObservedAt,
		arg.FCnt,
		arg.Detail,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCyclesBefore = `-- name: ListCyclesBefore :many
SELECT device_id, started_at, f_cnt, received_at, run_s, peak_current_a, level_start_mm, level_end_mm, pump_id, est_volume_l, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM cycle_events
WHERE device_id = $1 AND started_at < $2
ORDER BY started_at DESC
LIMIT $3
`

type ListCyclesBeforeParams struct {
	DeviceID  string
	StartedAt time.Time
	Limit     int32
}

func (q *Queries) ListCyclesBefore(ctx context.Context, arg ListCyclesBeforeParams) ([]CycleEvent, error) {
	rows, err := q.db.Query(ctx, listCyclesBefore, arg.DeviceID, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CycleEvent{}
	for rows.Next() {
		var i CycleEvent
		if err := rows.Scan(
			&i.DeviceID,
			&i.StartedAt,
			&i.FCnt,
			&i.ReceivedAt,
			&i.RunS,
			&i.PeakCurrentA,
			&i.LevelStartMm,
			&i.LevelEndMm,
			&i.PumpID,
			&i.EstVolumeL,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetections = `-- name: ListDetections :many
SELECT device_id, code, action, observed_at, f_cnt, detail, inserted_at FROM detections WHERE device_id = $1 ORDER BY observed_at, code, action
`

func (q *Queries) ListDetections(ctx context.Context, deviceID string) ([]Detection, error) {
	rows, err := q.db.Query(ctx, listDetections, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Detection{}
	for rows.Next() {
		var i Detection
		if err := rows.Scan(
			&i.DeviceID,
			&i.Code,
			&i.Action,
			&i.ObservedAt,
			&i.FCnt,
			&i.Detail,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsBefore = `-- name: ListReadingsBefore :many
SELECT device_id, ts, f_cnt, level_mm, temp_c, rh_pct, batt_mv, cycles_since_last, mains_ok, float_high, backup_ran, sensor_fault, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM readings
WHERE device_id = $1 AND ts < $2
ORDER BY ts DESC
LIMIT $3
`

type ListReadingsBeforeParams struct {
	DeviceID string
	Ts       time.Time
	Limit    int32
}

func (q *Queries) ListReadingsBefore(ctx context.Context, arg ListReadingsBeforeParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsBefore, arg.DeviceID, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reading{}
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.DeviceID,
			&i.Ts,
			&i.FCnt,
			&i.LevelMm,
			&i.TempC,
			&i.RhPct,
			&i.BattMv,
			&i.CyclesSinceLast,
			&i.MainsOk,
			&i.FloatHigh,
			&i.BackupRan,
			&i.SensorFault,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeCycleVolumes = `-- name: RecomputeCycleVolumes :execrows
UPDATE cycle_events c
SET est_volume_l = (h.pit_area_m2 * (c.level_end_mm - c.level_start_mm))::real
FROM devices d
JOIN homes h ON h.id = d.home_id
WHERE c.device_id = d.dev_eui AND d.dev_eui = $1 AND h.pit_area_m2 IS NOT NULL
`

// Backfill after an operator links a device to a home with a pit area.
func (q *Queries) RecomputeCycleVolumes(ctx context.Context, devEui string) (int64, error) {
	result, err := q.db.Exec(ctx, recomputeCycleVolumes, devEui)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
