// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDevice = `-- name: GetDevice :one
SELECT dev_eui, home_id, kind, name, installed_at, first_seen_at, last_seen_at FROM devices WHERE dev_eui = $1
`

func (q *Queries) GetDevice(ctx context.Context, devEui string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, devEui)
	var i Device
	err := row.Scan(
		&i.DevEui,
		&i.HomeID,
		&i.Kind,
		&i.Name,
		&i.InstalledAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT dev_eui, home_id, kind, name, installed_at, first_seen_at, last_seen_at FROM devices ORDER BY dev_eui
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DevEui,
			&i.HomeID,
			&i.Kind,
			&i.Name,
			&i.InstalledAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (dev_eui, home_id, kind, name, installed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (dev_eui) DO UPDATE
  SET home_id = EXCLUDED.home_id,
      kind = EXCLUDED.kind,
      name = EXCLUDED.name,
      installed_at = EXCLUDED.installed_at
RETURNING dev_eui, home_id, kind, name, installed_at, first_seen_at, last_seen_at
`

type UpsertDeviceParams struct {
	DevEui      string
	HomeID      uuid.NullUUID
	Kind        string
	Name        pgtype.Text
	InstalledAt sql.NullTime
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.DevEui,
		arg.HomeID,
		arg.Kind,
		arg.Name,
		arg.InstalledAt,
	)
	var i Device
	err := row.Scan(
		&i.DevEui,
		&i.HomeID,
		&i.Kind,
		&i.Name,
		&i.InstalledAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
