// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homes.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const linkDevice = `-- name: LinkDevice :exec
UPDATE devices SET home_id = $2 WHERE dev_eui = $1
`

type LinkDeviceParams struct {
	DevEui string
	HomeID uuid.NullUUID
}

func (q *Queries) LinkDevice(ctx context.Context, arg LinkDeviceParams) error {
	_, err := q.db.Exec(ctx, linkDevice, arg.DevEui, arg.HomeID)
	return err
}

const upsertHome = `-- name: UpsertHome :one
INSERT INTO homes (id, segment_id, pit_area_m2) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET segment_id = EXCLUDED.segment_id, pit_area_m2 = EXCLUDED.pit_area_m2
RETURNING id, segment_id, pit_area_m2, consent_at, owner_contact_encrypted, created_at
`

type UpsertHomeParams struct {
	ID        uuid.UUID
	SegmentID pgtype.Text
	PitAreaM2 sql.NullFloat64
}

func (q *Queries) UpsertHome(ctx context.Context, arg UpsertHomeParams) (Home, error) {
	row := q.db.QueryRow(ctx, upsertHome, arg.ID, arg.SegmentID, arg.PitAreaM2)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.PitAreaM2,
		&i.ConsentAt,
		&i.OwnerContactEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSegment = `-- name: UpsertSegment :exec
INSERT INTO segments (id, name, kind) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, kind = EXCLUDED.kind
`

type UpsertSegmentParams struct {
	ID   string
	Name string
	Kind string
}

func (q *Queries) UpsertSegment(ctx context.Context, arg UpsertSegmentParams) error {
	_, err := q.db.Exec(ctx, upsertSegment, arg.ID, arg.Name, arg.Kind)
	return err
}
