// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PumpKind string

const (
	PumpKindPrimary PumpKind = "primary"
	PumpKindBackup  PumpKind = "backup"
)

func (e *PumpKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PumpKind(s)
	case string:
		*e = PumpKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PumpKind: %T", src)
	}
	return nil
}

type NullPumpKind struct {
	PumpKind PumpKind
	Valid    bool // Valid is true if PumpKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPumpKind) Scan(value interface{}) error {
	if value == nil {
		ns.PumpKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PumpKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPumpKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PumpKind), nil
}

type AlarmEvent struct {
	DeviceID   string
	RaisedAt   time.Time
	FCnt       int64
	Code       int16
	Value      int32
	RssiDbm    pgtype.Int2
	SnrDb      pgtype.Float4
	Sf         pgtype.Int2
	GatewayID  pgtype.Text
	DedupID    uuid.NullUUID
	InsertedAt time.Time
}

type Alert struct {
	ID                    uuid.UUID
	DeviceID              string
	HomeID                uuid.NullUUID
	Code                  int16
	Severity              int16
	RaisedAt              time.Time
	LastSeenAt            time.Time
	Occurrences           int32
	AckedAt               sql.NullTime
	AckNote               pgtype.Text
	ResolvedAt            sql.NullTime
	ResolveReason         pgtype.Text
	Message               string
	Source                string
	TriggerKey            string
	NotifyState           string
	NotifyAttempts        int32
	NotifiedAt            sql.NullTime
	ResolveNotifyState    string
	ResolveNotifyAttempts int32
	UpdatedAt             time.Time
	InsertedAt            time.Time
}

type ConsumerWatermark struct {
	Consumer   string
	Source     string
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type CycleEvent struct {
	DeviceID     string
	StartedAt    time.Time
	FCnt         int64
	ReceivedAt   time.Time
	RunS         int32
	PeakCurrentA float32
	LevelStartMm int32
	LevelEndMm   int32
	PumpID       PumpKind
	EstVolumeL   pgtype.Float4
	RssiDbm      pgtype.Int2
	SnrDb        pgtype.Float4
	Sf           pgtype.Int2
	GatewayID    pgtype.Text
	DedupID      uuid.NullUUID
	InsertedAt   time.Time
}

type Detection struct {
	DeviceID   string
	Code       int16
	Action     int16
	ObservedAt time.Time
	FCnt       int64
	Detail     []byte
	InsertedAt time.Time
}

type Device struct {
	DevEui      string
	HomeID      uuid.NullUUID
	Kind        string
	Name        pgtype.Text
	InstalledAt sql.NullTime
	FirstSeenAt time.Time
	LastSeenAt  sql.NullTime
}

type Home struct {
	ID                    uuid.UUID
	SegmentID             pgtype.Text
	PitAreaM2             sql.NullFloat64
	ConsentAt             sql.NullTime
	OwnerContactEncrypted []byte
	CreatedAt             time.Time
}

type Reading struct {
	DeviceID        string
	Ts              time.Time
	FCnt            int64
	LevelMm         int32
	TempC           pgtype.Float4
	RhPct           pgtype.Int2
	BattMv          pgtype.Int4
	CyclesSinceLast int16
	MainsOk         bool
	FloatHigh       bool
	BackupRan       bool
	SensorFault     bool
	RssiDbm         pgtype.Int2
	SnrDb           pgtype.Float4
	Sf              pgtype.Int2
	GatewayID       pgtype.Text
	DedupID         uuid.NullUUID
	InsertedAt      time.Time
}

type Segment struct {
	ID        string
	Name      string
	Geometry  []byte
	CreatedAt time.Time
}

type StormSummary struct {
	DeviceID        string
	WindowEnd       time.Time
	FCnt            int64
	WindowS         int32
	CycleCount      int32
	TotalRunS       int32
	MaxPeakCurrentA float32
	MinLevelMm      int32
	RssiDbm         pgtype.Int2
	SnrDb           pgtype.Float4
	Sf              pgtype.Int2
	GatewayID       pgtype.Text
	DedupID         uuid.NullUUID
	InsertedAt      time.Time
}
