// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenAlertsForHome = `-- name: CountOpenAlertsForHome :one
SELECT count(*)::bigint FROM alerts WHERE home_id = $1 AND resolved_at IS NULL
`

func (q *Queries) CountOpenAlertsForHome(ctx context.Context, homeID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlertsForHome, homeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const gatewayListSegments = `-- name: GatewayListSegments :many

SELECT s.id, s.name, s.kind, s.geometry,
       (SELECT count(DISTINCT d.home_id) FROM devices d JOIN homes h ON h.id = d.home_id
        WHERE h.segment_id = s.id AND d.kind = 'house')::bigint AS home_count
FROM segments s
ORDER BY s.id
`

type GatewayListSegmentsRow struct {
	ID        string
	Name      string
	Kind      string
	Geometry  []byte
	HomeCount int64
}

// api-gateway (Phase 5) reads. The gateway is read-only: it never writes
// telemetry or alerts. Per-home rows are reachable only through an
// owner-scoped query (auth_subject = Clerk user id) or as input to an
// internal/privacy aggregate (ADR 0005). "Linked" homes are homes with at
// least one device whose home_id points at them; unlinked devices never count.
func (q *Queries) GatewayListSegments(ctx context.Context) ([]GatewayListSegmentsRow, error) {
	rows, err := q.db.Query(ctx, gatewayListSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayListSegmentsRow{}
	for rows.Next() {
		var i GatewayListSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Geometry,
			&i.HomeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHomeLatestBaseflow = `-- name: GetHomeLatestBaseflow :one
SELECT m.baseflow_cpd::float8 AS baseflow_cpd
FROM home_storm_metrics m JOIN storm_events s ON s.id = m.storm_id
WHERE m.home_id = $1 AND m.baseflow_cpd IS NOT NULL
ORDER BY s.started_at DESC, s.id DESC
LIMIT 1
`

// Baseflow storm-analytics used for the home's most recent storm.
func (q *Queries) GetHomeLatestBaseflow(ctx context.Context, homeID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getHomeLatestBaseflow, homeID)
	var baseflow_cpd float64
	err := row.Scan(&baseflow_cpd)
	return baseflow_cpd, err
}

const getHomeLatestReading = `-- name: GetHomeLatestReading :one
SELECT r.ts, r.batt_mv, r.mains_ok
FROM readings r
WHERE r.device_id IN (SELECT d.dev_eui FROM devices d WHERE d.home_id = $1 AND d.kind = 'house')
ORDER BY r.ts DESC
LIMIT 1
`

type GetHomeLatestReadingRow struct {
	Ts      time.Time
	BattMv  pgtype.Int4
	MainsOk bool
}

// Newest heartbeat across the home's house devices.
func (q *Queries) GetHomeLatestReading(ctx context.Context, homeID uuid.NullUUID) (GetHomeLatestReadingRow, error) {
	row := q.db.QueryRow(ctx, getHomeLatestReading, homeID)
	var i GetHomeLatestReadingRow
	err := row.Scan(&i.Ts, &i.BattMv, &i.MainsOk)
	return i, err
}

const getOwnedHome = `-- name: GetOwnedHome :one
SELECT h.id, h.segment_id, h.pit_area_m2, h.consent_at, h.owner_contact_encrypted, h.created_at FROM homes h
JOIN home_owners o ON o.home_id = h.id
WHERE o.auth_subject = $1 AND h.id = $2
`

type GetOwnedHomeParams struct {
	AuthSubject string
	HomeID      uuid.UUID
}

func (q *Queries) GetOwnedHome(ctx context.Context, arg GetOwnedHomeParams) (Home, error) {
	row := q.db.QueryRow(ctx, getOwnedHome, arg.AuthSubject, arg.HomeID)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.PitAreaM2,
		&i.ConsentAt,
		&i.OwnerContactEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const getStormEventByID = `-- name: GetStormEventByID :one
SELECT id, started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status, inserted_at, updated_at FROM storm_events WHERE id = $1
`

func (q *Queries) GetStormEventByID(ctx context.Context, id uuid.UUID) (StormEvent, error) {
	row := q.db.QueryRow(ctx, getStormEventByID, id)
	var i StormEvent
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalRainMm,
		&i.PeakIntensityMmH,
		&i.RainSource,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertsChangedSince = `-- name: ListAlertsChangedSince :many
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a JOIN homes h ON h.id = a.home_id
WHERE a.updated_at > $1
ORDER BY a.updated_at, a.id
`

type ListAlertsChangedSinceRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

// Alert rows on homes that changed after @after; routed to owners only.
func (q *Queries) ListAlertsChangedSince(ctx context.Context, after time.Time) ([]ListAlertsChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, listAlertsChangedSince, after)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsChangedSinceRow{}
	for rows.Next() {
		var i ListAlertsChangedSinceRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.DeviceID,
			&i.Alert.HomeID,
			&i.Alert.Code,
			&i.Alert.Severity,
			&i.Alert.RaisedAt,
			&i.Alert.LastSeenAt,
			&i.Alert.Occurrences,
			&i.Alert.AckedAt,
			&i.Alert.AckNote,
			&i.Alert.ResolvedAt,
			&i.Alert.ResolveReason,
			&i.Alert.Message,
			&i.Alert.Source,
			&i.Alert.TriggerKey,
			&i.Alert.NotifyState,
			&i.Alert.NotifyAttempts,
			&i.Alert.NotifiedAt,
			&i.Alert.ResolveNotifyState,
			&i.Alert.ResolveNotifyAttempts,
			&i.Alert.UpdatedAt,
			&i.Alert.InsertedAt,
			&i.SegmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeDevices = `-- name: ListHomeDevices :many
SELECT dev_eui, home_id, kind, name, installed_at, first_seen_at, last_seen_at FROM devices WHERE home_id = $1 ORDER BY dev_eui
`

func (q *Queries) ListHomeDevices(ctx context.Context, homeID uuid.NullUUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listHomeDevices, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DevEui,
			&i.HomeID,
			&i.Kind,
			&i.Name,
			&i.InstalledAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeStormMetrics = `-- name: ListHomeStormMetrics :many
SELECT m.storm_id, m.home_id, m.lag_min, m.recession_min, m.volume_l, m.cycles, s.started_at
FROM home_storm_metrics m JOIN storm_events s ON s.id = m.storm_id
WHERE m.home_id = $1
ORDER BY s.started_at DESC, s.id DESC
LIMIT $2
`

type ListHomeStormMetricsParams struct {
	HomeID uuid.UUID
	Lim    int32
}

type ListHomeStormMetricsRow struct {
	StormID      uuid.UUID
	HomeID       uuid.UUID
	LagMin       pgtype.Float8
	RecessionMin pgtype.Float8
	VolumeL      float64
	Cycles       int32
	StartedAt    time.Time
}

func (q *Queries) ListHomeStormMetrics(ctx context.Context, arg ListHomeStormMetricsParams) ([]ListHomeStormMetricsRow, error) {
	rows, err := q.db.Query(ctx, listHomeStormMetrics, arg.HomeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeStormMetricsRow{}
	for rows.Next() {
		var i ListHomeStormMetricsRow
		if err := rows.Scan(
			&i.StormID,
			&i.HomeID,
			&i.LagMin,
			&i.RecessionMin,
			&i.VolumeL,
			&i.Cycles,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedHomes = `-- name: ListOwnedHomes :many
SELECT h.id, h.segment_id, h.pit_area_m2, h.consent_at, h.owner_contact_encrypted, h.created_at FROM homes h
JOIN home_owners o ON o.home_id = h.id
WHERE o.auth_subject = $1
ORDER BY h.created_at, h.id
`

func (q *Queries) ListOwnedHomes(ctx context.Context, authSubject string) ([]Home, error) {
	rows, err := q.db.Query(ctx, listOwnedHomes, authSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Home{}
	for rows.Next() {
		var i Home
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.PitAreaM2,
			&i.ConsentAt,
			&i.OwnerContactEncrypted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerActiveAlerts = `-- name: ListOwnerActiveAlerts :many
SELECT a.id, a.device_id, a.home_id, a.code, a.severity, a.raised_at, a.last_seen_at, a.occurrences, a.acked_at, a.ack_note, a.resolved_at, a.resolve_reason, a.message, a.source, a.trigger_key, a.notify_state, a.notify_attempts, a.notified_at, a.resolve_notify_state, a.resolve_notify_attempts, a.updated_at, a.inserted_at, h.segment_id
FROM alerts a
JOIN homes h ON h.id = a.home_id
JOIN home_owners o ON o.home_id = a.home_id
WHERE o.auth_subject = $1 AND a.resolved_at IS NULL
  AND ($2::uuid IS NULL OR a.home_id = $2)
ORDER BY a.raised_at DESC, a.id
`

type ListOwnerActiveAlertsParams struct {
	AuthSubject string
	HomeID      uuid.NullUUID
}

type ListOwnerActiveAlertsRow struct {
	Alert     Alert
	SegmentID pgtype.Text
}

func (q *Queries) ListOwnerActiveAlerts(ctx context.Context, arg ListOwnerActiveAlertsParams) ([]ListOwnerActiveAlertsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerActiveAlerts, arg.AuthSubject, arg.HomeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerActiveAlertsRow{}
	for rows.Next() {
		var i ListOwnerActiveAlertsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.DeviceID,
			&i.Alert.HomeID,
			&i.Alert.Code,
			&i.Alert.Severity,
			&i.Alert.RaisedAt,
			&i.Alert.LastSeenAt,
			&i.Alert.Occurrences,
			&i.Alert.AckedAt,
			&i.Alert.AckNote,
			&i.Alert.ResolvedAt,
			&i.Alert.ResolveReason,
			&i.Alert.Message,
			&i.Alert.Source,
			&i.Alert.TriggerKey,
			&i.Alert.NotifyState,
			&i.Alert.NotifyAttempts,
			&i.Alert.NotifiedAt,
			&i.Alert.ResolveNotifyState,
			&i.Alert.ResolveNotifyAttempts,
			&i.Alert.UpdatedAt,
			&i.Alert.InsertedAt,
			&i.SegmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersOfHomes = `-- name: ListOwnersOfHomes :many
SELECT auth_subject, home_id FROM home_owners WHERE home_id = ANY($1::uuid[])
`

type ListOwnersOfHomesRow struct {
	AuthSubject string
	HomeID      uuid.UUID
}

func (q *Queries) ListOwnersOfHomes(ctx context.Context, homeIds []uuid.UUID) ([]ListOwnersOfHomesRow, error) {
	rows, err := q.db.Query(ctx, listOwnersOfHomes, homeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnersOfHomesRow{}
	for rows.Next() {
		var i ListOwnersOfHomesRow
		if err := rows.Scan(&i.AuthSubject, &i.HomeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotStormEvents = `-- name: ListSnapshotStormEvents :many
SELECT id, started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status, inserted_at, updated_at FROM storm_events
WHERE status = 'open'
   OR id IN (SELECT r.id FROM storm_events r ORDER BY r.started_at DESC, r.id DESC LIMIT $1)
ORDER BY started_at, id
`

// Open storms plus the most recent ones, for a WatchNeighbourhood snapshot.
func (q *Queries) ListSnapshotStormEvents(ctx context.Context, recent int32) ([]StormEvent, error) {
	rows, err := q.db.Query(ctx, listSnapshotStormEvents, recent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StormEvent{}
	for rows.Next() {
		var i StormEvent
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TotalRainMm,
			&i.PeakIntensityMmH,
			&i.RainSource,
			&i.Status,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStormEventsChangedSince = `-- name: ListStormEventsChangedSince :many
SELECT id, started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status, inserted_at, updated_at FROM storm_events WHERE updated_at > $1 ORDER BY updated_at, id
`

func (q *Queries) ListStormEventsChangedSince(ctx context.Context, after time.Time) ([]StormEvent, error) {
	rows, err := q.db.Query(ctx, listStormEventsChangedSince, after)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StormEvent{}
	for rows.Next() {
		var i StormEvent
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TotalRainMm,
			&i.PeakIntensityMmH,
			&i.RainSource,
			&i.Status,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStormEventsPage = `-- name: ListStormEventsPage :many
SELECT id, started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status, inserted_at, updated_at FROM storm_events
WHERE ($1::timestamptz IS NULL OR started_at >= $1)
  AND ($2::timestamptz IS NULL OR started_at < $2)
  AND ($3::timestamptz IS NULL
       OR (started_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY started_at DESC, id DESC
LIMIT $5
`

type ListStormEventsPageParams struct {
	Since           sql.NullTime
	Until           sql.NullTime
	CursorStartedAt sql.NullTime
	CursorID        uuid.NullUUID
	Lim             int32
}

// Newest first, keyset-paged on (started_at, id).
func (q *Queries) ListStormEventsPage(ctx context.Context, arg ListStormEventsPageParams) ([]StormEvent, error) {
	rows, err := q.db.Query(ctx, listStormEventsPage,
		arg.Since,
		arg.Until,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StormEvent{}
	for rows.Next() {
		var i StormEvent
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TotalRainMm,
			&i.PeakIntensityMmH,
			&i.RainSource,
			&i.Status,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStormHomeMetrics = `-- name: ListStormHomeMetrics :many
SELECT h.segment_id::text AS segment_id, m.home_id, m.volume_l, m.lag_min, m.recession_min
FROM home_storm_metrics m
JOIN homes h ON h.id = m.home_id
WHERE m.storm_id = $1 AND h.segment_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM devices d WHERE d.home_id = h.id AND d.kind = 'house')
ORDER BY h.segment_id, m.home_id
`

type ListStormHomeMetricsRow struct {
	SegmentID    string
	HomeID       uuid.UUID
	VolumeL      float64
	LagMin       pgtype.Float8
	RecessionMin pgtype.Float8
}

// Input to privacy.AggregateStorm only; never returned to a caller as rows.
func (q *Queries) ListStormHomeMetrics(ctx context.Context, stormID uuid.UUID) ([]ListStormHomeMetricsRow, error) {
	rows, err := q.db.Query(ctx, listStormHomeMetrics, stormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStormHomeMetricsRow{}
	for rows.Next() {
		var i ListStormHomeMetricsRow
		if err := rows.Scan(
			&i.SegmentID,
			&i.HomeID,
			&i.VolumeL,
			&i.LagMin,
			&i.RecessionMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neighbourhoodClock = `-- name: NeighbourhoodClock :one
SELECT coalesce(least(max(d.last_seen_at), now()), now())::timestamptz AS clock
FROM devices d
WHERE d.home_id IS NOT NULL AND d.kind = 'house'
`

// The event-time "now" of the neighbourhood: the newest event from a linked
// house device, never later than the wall clock. Anchoring the live status
// window here makes a replay of a past storm animate like a live one.
func (q *Queries) NeighbourhoodClock(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, neighbourhoodClock)
	var clock time.Time
	err := row.Scan(&clock)
	return clock, err
}

const ownsAlert = `-- name: OwnsAlert :one
SELECT EXISTS (
  SELECT 1 FROM alerts a JOIN home_owners o ON o.home_id = a.home_id
  WHERE o.auth_subject = $1 AND a.id = $2
) AS owned
`

type OwnsAlertParams struct {
	AuthSubject string
	AlertID     uuid.UUID
}

func (q *Queries) OwnsAlert(ctx context.Context, arg OwnsAlertParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsAlert, arg.AuthSubject, arg.AlertID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const ownsHome = `-- name: OwnsHome :one
SELECT EXISTS (
  SELECT 1 FROM home_owners WHERE auth_subject = $1 AND home_id = $2
) AS owned
`

type OwnsHomeParams struct {
	AuthSubject string
	HomeID      uuid.UUID
}

func (q *Queries) OwnsHome(ctx context.Context, arg OwnsHomeParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsHome, arg.AuthSubject, arg.HomeID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const segmentActivity = `-- name: SegmentActivity :many
SELECT h.segment_id::text AS segment_id,
       count(DISTINCT h.id)::bigint AS homes_reporting,
       coalesce(sum(r.cycles_since_last), 0)::bigint AS cycles
FROM readings r
JOIN devices d ON d.dev_eui = r.device_id
JOIN homes h ON h.id = d.home_id
WHERE r.ts > $1 AND r.ts <= $2
  AND d.kind = 'house' AND h.segment_id IS NOT NULL
GROUP BY h.segment_id
`

type SegmentActivityParams struct {
	WindowStart time.Time
	WindowEnd   time.Time
}

type SegmentActivityRow struct {
	SegmentID      string
	HomesReporting int64
	Cycles         int64
}

// Input to privacy.AggregateStatus: distinct linked homes with a heartbeat in
// (window_start, window_end] and the cycles those heartbeats report
// (cycles_since_last counts storm-mode cycles too).
func (q *Queries) SegmentActivity(ctx context.Context, arg SegmentActivityParams) ([]SegmentActivityRow, error) {
	rows, err := q.db.Query(ctx, segmentActivity, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentActivityRow{}
	for rows.Next() {
		var i SegmentActivityRow
		if err := rows.Scan(&i.SegmentID, &i.HomesReporting, &i.Cycles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentOpenAlertCounts = `-- name: SegmentOpenAlertCounts :many
SELECT h.segment_id::text AS segment_id, count(*)::bigint AS active_alerts
FROM alerts a JOIN homes h ON h.id = a.home_id
WHERE a.resolved_at IS NULL AND h.segment_id IS NOT NULL
GROUP BY h.segment_id
`

type SegmentOpenAlertCountsRow struct {
	SegmentID    string
	ActiveAlerts int64
}

// Input to privacy.AggregateStatus: open alerts on linked homes per segment.
func (q *Queries) SegmentOpenAlertCounts(ctx context.Context) ([]SegmentOpenAlertCountsRow, error) {
	rows, err := q.db.Query(ctx, segmentOpenAlertCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentOpenAlertCountsRow{}
	for rows.Next() {
		var i SegmentOpenAlertCountsRow
		if err := rows.Scan(&i.SegmentID, &i.ActiveAlerts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
