// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const seedHomeOwner = `-- name: SeedHomeOwner :execrows
INSERT INTO home_owners (auth_subject, home_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SeedHomeOwnerParams struct {
	AuthSubject string
	HomeID      uuid.UUID
}

func (q *Queries) SeedHomeOwner(ctx context.Context, arg SeedHomeOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, seedHomeOwner, arg.AuthSubject, arg.HomeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedSegment = `-- name: SeedSegment :exec

INSERT INTO segments (id, name, kind, geometry) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, kind = EXCLUDED.kind, geometry = EXCLUDED.geometry
`

type SeedSegmentParams struct {
	ID       string
	Name     string
	Kind     string
	Geometry []byte
}

// Demo seed (cmd/seed): operator tooling only, never used by a service.
// Homes and devices go through UpsertHome / UpsertDevice.
func (q *Queries) SeedSegment(ctx context.Context, arg SeedSegmentParams) error {
	_, err := q.db.Exec(ctx, seedSegment,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Geometry,
	)
	return err
}
