// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storms.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHomeStormMetrics = `-- name: DeleteHomeStormMetrics :exec
DELETE FROM home_storm_metrics WHERE storm_id = $1 AND home_id = $2
`

type DeleteHomeStormMetricsParams struct {
	StormID uuid.UUID
	HomeID  uuid.UUID
}

func (q *Queries) DeleteHomeStormMetrics(ctx context.Context, arg DeleteHomeStormMetricsParams) error {
	_, err := q.db.Exec(ctx, deleteHomeStormMetrics, arg.StormID, arg.HomeID)
	return err
}

const deleteStormEvent = `-- name: DeleteStormEvent :exec
DELETE FROM storm_events WHERE id = $1
`

func (q *Queries) DeleteStormEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStormEvent, id)
	return err
}

const getLinkedHouseDevice = `-- name: GetLinkedHouseDevice :one
SELECT d.dev_eui, h.id AS home_id, coalesce(h.pit_area_m2, 0)::float8 AS pit_area_m2, d.last_seen_at
FROM devices d
JOIN homes h ON h.id = d.home_id
WHERE d.kind = 'house' AND d.dev_eui = $1
`

type GetLinkedHouseDeviceRow struct {
	DevEui     string
	HomeID     uuid.UUID
	PitAreaM2  float64
	LastSeenAt sql.NullTime
}

func (q *Queries) GetLinkedHouseDevice(ctx context.Context, devEui string) (GetLinkedHouseDeviceRow, error) {
	row := q.db.QueryRow(ctx, getLinkedHouseDevice, devEui)
	var i GetLinkedHouseDeviceRow
	err := row.Scan(
		&i.DevEui,
		&i.HomeID,
		&i.PitAreaM2,
		&i.LastSeenAt,
	)
	return i, err
}

const insertStormEvent = `-- name: InsertStormEvent :one
INSERT INTO storm_events (started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertStormEventParams struct {
	StartedAt        time.Time
	EndedAt          sql.NullTime
	TotalRainMm      float64
	PeakIntensityMmH float64
	RainSource       string
	Status           string
}

func (q *Queries) InsertStormEvent(ctx context.Context, arg InsertStormEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertStormEvent,
		arg.StartedAt,
		arg.EndedAt,
		arg.TotalRainMm,
		arg.PeakIntensityMmH,
		arg.RainSource,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCycleEventsForDevice = `-- name: ListCycleEventsForDevice :many
SELECT started_at, run_s, level_start_mm, level_end_mm, pump_id FROM cycle_events
WHERE device_id = $1 AND started_at >= $2 AND started_at < $3
ORDER BY started_at, f_cnt
`

type ListCycleEventsForDeviceParams struct {
	DeviceID string
	FromTs   time.Time
	ToTs     time.Time
}

type ListCycleEventsForDeviceRow struct {
	StartedAt    time.Time
	RunS         int32
	LevelStartMm int32
	LevelEndMm   int32
	PumpID       PumpKind
}

func (q *Queries) ListCycleEventsForDevice(ctx context.Context, arg ListCycleEventsForDeviceParams) ([]ListCycleEventsForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listCycleEventsForDevice, arg.DeviceID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCycleEventsForDeviceRow{}
	for rows.Next() {
		var i ListCycleEventsForDeviceRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.RunS,
			&i.LevelStartMm,
			&i.LevelEndMm,
			&i.PumpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeMetricsForStorm = `-- name: ListHomeMetricsForStorm :many
SELECT storm_id, home_id, lag_min, recession_min, volume_l, cycles, baseflow_cpd, computed_at, inflow_est_l, pump_rate_lps, pump_rate_source FROM home_storm_metrics WHERE storm_id = $1 ORDER BY home_id
`

func (q *Queries) ListHomeMetricsForStorm(ctx context.Context, stormID uuid.UUID) ([]HomeStormMetric, error) {
	rows, err := q.db.Query(ctx, listHomeMetricsForStorm, stormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomeStormMetric{}
	for rows.Next() {
		var i HomeStormMetric
		if err := rows.Scan(
			&i.StormID,
			&i.HomeID,
			&i.LagMin,
			&i.RecessionMin,
			&i.VolumeL,
			&i.Cycles,
			&i.BaseflowCpd,
			&i.ComputedAt,
			&i.InflowEstL,
			&i.PumpRateLps,
			&i.PumpRateSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevelsForDevice = `-- name: ListLevelsForDevice :many
SELECT ts, level_mm FROM readings
WHERE device_id = $1 AND ts >= $2 AND ts < $3 AND NOT sensor_fault
ORDER BY ts, f_cnt
`

type ListLevelsForDeviceParams struct {
	DeviceID string
	FromTs   time.Time
	ToTs     time.Time
}

type ListLevelsForDeviceRow struct {
	Ts      time.Time
	LevelMm int32
}

func (q *Queries) ListLevelsForDevice(ctx context.Context, arg ListLevelsForDeviceParams) ([]ListLevelsForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listLevelsForDevice, arg.DeviceID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLevelsForDeviceRow{}
	for rows.Next() {
		var i ListLevelsForDeviceRow
		if err := rows.Scan(&i.Ts, &i.LevelMm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedHouseDevices = `-- name: ListLinkedHouseDevices :many
SELECT d.dev_eui, h.id AS home_id, coalesce(h.pit_area_m2, 0)::float8 AS pit_area_m2, d.last_seen_at
FROM devices d
JOIN homes h ON h.id = d.home_id
WHERE d.kind = 'house'
ORDER BY h.id, d.dev_eui
`

type ListLinkedHouseDevicesRow struct {
	DevEui     string
	HomeID     uuid.UUID
	PitAreaM2  float64
	LastSeenAt sql.NullTime
}

// House nodes linked to a home; last_seen_at is the newest event time ingest saw.
func (q *Queries) ListLinkedHouseDevices(ctx context.Context) ([]ListLinkedHouseDevicesRow, error) {
	rows, err := q.db.Query(ctx, listLinkedHouseDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedHouseDevicesRow{}
	for rows.Next() {
		var i ListLinkedHouseDevicesRow
		if err := rows.Scan(
			&i.DevEui,
			&i.HomeID,
			&i.PitAreaM2,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStormEventsOverlapping = `-- name: ListStormEventsOverlapping :many
SELECT id, started_at, ended_at, total_rain_mm, peak_intensity_mm_h, rain_source, status, inserted_at, updated_at FROM storm_events
WHERE started_at < $1::timestamptz AND coalesce(ended_at, 'infinity'::timestamptz) > $2::timestamptz
ORDER BY started_at, id
`

type ListStormEventsOverlappingParams struct {
	ToTs   time.Time
	FromTs time.Time
}

// Storms whose [started_at, ended_at] meets [from_ts, to_ts); open storms reach forward indefinitely.
func (q *Queries) ListStormEventsOverlapping(ctx context.Context, arg ListStormEventsOverlappingParams) ([]StormEvent, error) {
	rows, err := q.db.Query(ctx, listStormEventsOverlapping, arg.ToTs, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StormEvent{}
	for rows.Next() {
		var i StormEvent
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TotalRainMm,
			&i.PeakIntensityMmH,
			&i.RainSource,
			&i.Status,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStormSummariesForDevice = `-- name: ListStormSummariesForDevice :many
SELECT window_end, window_s, cycle_count, total_run_s FROM storm_summaries
WHERE device_id = $1 AND window_end >= $2 AND window_end < $3
ORDER BY window_end, f_cnt
`

type ListStormSummariesForDeviceParams struct {
	DeviceID string
	FromTs   time.Time
	ToTs     time.Time
}

type ListStormSummariesForDeviceRow struct {
	WindowEnd  time.Time
	WindowS    int32
	CycleCount int32
	TotalRunS  int32
}

func (q *Queries) ListStormSummariesForDevice(ctx context.Context, arg ListStormSummariesForDeviceParams) ([]ListStormSummariesForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listStormSummariesForDevice, arg.DeviceID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStormSummariesForDeviceRow{}
	for rows.Next() {
		var i ListStormSummariesForDeviceRow
		if err := rows.Scan(
			&i.WindowEnd,
			&i.WindowS,
			&i.CycleCount,
			&i.TotalRunS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollRainfall = `-- name: PollRainfall :many

WITH bound AS (
  SELECT max(updated_at) AS hi FROM (
    SELECT DISTINCT updated_at FROM rainfall
    WHERE updated_at > $1 AND updated_at <= now() - make_interval(secs => $2::float8)
    ORDER BY updated_at LIMIT $3
  ) g
)
SELECT r.source, r.station_id, r.ts, r.interval_s, r.mm, r.inserted_at, r.updated_at FROM rainfall r, bound
WHERE r.updated_at > $1 AND r.updated_at <= bound.hi
ORDER BY r.updated_at, r.source, r.station_id, r.ts
`

type PollRainfallParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

// Phase 4 storm-analytics: storm_events and home_storm_metrics maintenance.
// storm-analytics is the single writer of both tables.
// Polled by updated_at (see migration 0005): rewrites must reach the consumer.
func (q *Queries) PollRainfall(ctx context.Context, arg PollRainfallParams) ([]Rainfall, error) {
	rows, err := q.db.Query(ctx, pollRainfall, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rainfall{}
	for rows.Next() {
		var i Rainfall
		if err := rows.Scan(
			&i.Source,
			&i.StationID,
			&i.Ts,
			&i.IntervalS,
			&i.Mm,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStormEvent = `-- name: UpdateStormEvent :exec
UPDATE storm_events
SET started_at = $1, ended_at = $2, total_rain_mm = $3,
    peak_intensity_mm_h = $4, rain_source = $5, status = $6,
    updated_at = now()
WHERE id = $7
`

type UpdateStormEventParams struct {
	StartedAt        time.Time
	EndedAt          sql.NullTime
	TotalRainMm      float64
	PeakIntensityMmH float64
	RainSource       string
	Status           string
	ID               uuid.UUID
}

func (q *Queries) UpdateStormEvent(ctx context.Context, arg UpdateStormEventParams) error {
	_, err := q.db.Exec(ctx, updateStormEvent,
		arg.StartedAt,
		arg.EndedAt,
		arg.TotalRainMm,
		arg.PeakIntensityMmH,
		arg.RainSource,
		arg.Status,
		arg.ID,
	)
	return err
}

const upsertHomeStormMetrics = `-- name: UpsertHomeStormMetrics :exec
INSERT INTO home_storm_metrics (storm_id, home_id, lag_min, recession_min, volume_l, cycles, baseflow_cpd, inflow_est_l, pump_rate_lps, pump_rate_source, computed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (storm_id, home_id) DO UPDATE
  SET lag_min = EXCLUDED.lag_min, recession_min = EXCLUDED.recession_min, volume_l = EXCLUDED.volume_l,
      cycles = EXCLUDED.cycles, baseflow_cpd = EXCLUDED.baseflow_cpd,
      inflow_est_l = EXCLUDED.inflow_est_l, pump_rate_lps = EXCLUDED.pump_rate_lps,
      pump_rate_source = EXCLUDED.pump_rate_source, computed_at = now()
`

type UpsertHomeStormMetricsParams struct {
	StormID        uuid.UUID
	HomeID         uuid.UUID
	LagMin         pgtype.Float8
	RecessionMin   pgtype.Float8
	VolumeL        float64
	Cycles         int32
	BaseflowCpd    pgtype.Float8
	InflowEstL     pgtype.Float8
	PumpRateLps    pgtype.Float8
	PumpRateSource pgtype.Text
}

func (q *Queries) UpsertHomeStormMetrics(ctx context.Context, arg UpsertHomeStormMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertHomeStormMetrics,
		arg.StormID,
		arg.HomeID,
		arg.LagMin,
		arg.RecessionMin,
		arg.VolumeL,
		arg.Cycles,
		arg.BaseflowCpd,
		arg.InflowEstL,
		arg.PumpRateLps,
		arg.PumpRateSource,
	)
	return err
}
