// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package sqlcgen

import (
	"context"
	"time"
)

const countAlarmEvents = `-- name: CountAlarmEvents :one
SELECT count(*) FROM alarm_events
`

func (q *Queries) CountAlarmEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAlarmEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCycleEvents = `-- name: CountCycleEvents :one
SELECT count(*) FROM cycle_events
`

func (q *Queries) CountCycleEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCycleEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRainGaugeUplinks = `-- name: CountRainGaugeUplinks :one
SELECT count(*) FROM rain_gauge_uplinks
`

func (q *Queries) CountRainGaugeUplinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRainGaugeUplinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReadings = `-- name: CountReadings :one
SELECT count(*) FROM readings
`

func (q *Queries) CountReadings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReadings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStormSummaries = `-- name: CountStormSummaries :one
SELECT count(*) FROM storm_summaries
`

func (q *Queries) CountStormSummaries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStormSummaries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fCntStatsByDevice = `-- name: FCntStatsByDevice :many
SELECT device_id, max(f_cnt)::bigint AS max_f_cnt, count(*)::bigint AS rows
FROM (
  SELECT device_id, f_cnt FROM readings
  UNION ALL SELECT device_id, f_cnt FROM cycle_events
  UNION ALL SELECT device_id, f_cnt FROM storm_summaries
  UNION ALL SELECT device_id, f_cnt FROM alarm_events
  UNION ALL SELECT device_id, f_cnt FROM rain_gauge_uplinks
) u
GROUP BY device_id
ORDER BY device_id
`

type FCntStatsByDeviceRow struct {
	DeviceID string
	MaxFCnt  int64
	Rows     int64
}

// Rows and highest frame counter per device across every telemetry table;
// with contiguous counters rows == max_f_cnt + 1.
func (q *Queries) FCntStatsByDevice(ctx context.Context) ([]FCntStatsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, fCntStatsByDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FCntStatsByDeviceRow{}
	for rows.Next() {
		var i FCntStatsByDeviceRow
		if err := rows.Scan(&i.DeviceID, &i.MaxFCnt, &i.Rows); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCycleEvent = `-- name: GetCycleEvent :one
SELECT device_id, started_at, f_cnt, received_at, run_s, peak_current_a, level_start_mm, level_end_mm, pump_id, est_volume_l, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM cycle_events WHERE device_id = $1 AND f_cnt = $2
`

type GetCycleEventParams struct {
	DeviceID string
	FCnt     int64
}

func (q *Queries) GetCycleEvent(ctx context.Context, arg GetCycleEventParams) (CycleEvent, error) {
	row := q.db.QueryRow(ctx, getCycleEvent, arg.DeviceID, arg.FCnt)
	var i CycleEvent
	err := row.Scan(
		&i.DeviceID,
		&i.StartedAt,
		&i.FCnt,
		&i.ReceivedAt,
		&i.RunS,
		&i.PeakCurrentA,
		&i.LevelStartMm,
		&i.LevelEndMm,
		&i.PumpID,
		&i.EstVolumeL,
		&i.RssiDbm,
		&i.SnrDb,
		&i.Sf,
		&i.GatewayID,
		&i.DedupID,
		&i.InsertedAt,
	)
	return i, err
}

const listReadingsForDevice = `-- name: ListReadingsForDevice :many
SELECT device_id, ts, f_cnt, level_mm, temp_c, rh_pct, batt_mv, cycles_since_last, mains_ok, float_high, backup_ran, sensor_fault, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM readings WHERE device_id = $1 AND ts >= $2 AND ts < $3 ORDER BY ts
`

type ListReadingsForDeviceParams struct {
	DeviceID string
	Ts       time.Time
	Ts_2     time.Time
}

func (q *Queries) ListReadingsForDevice(ctx context.Context, arg ListReadingsForDeviceParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsForDevice, arg.DeviceID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reading{}
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.DeviceID,
			&i.Ts,
			&i.FCnt,
			&i.LevelMm,
			&i.TempC,
			&i.RhPct,
			&i.BattMv,
			&i.CyclesSinceLast,
			&i.MainsOk,
			&i.FloatHigh,
			&i.BackupRan,
			&i.SensorFault,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumStormSummaryCycles = `-- name: SumStormSummaryCycles :one
SELECT coalesce(sum(cycle_count), 0)::bigint AS cycles FROM storm_summaries
`

func (q *Queries) SumStormSummaryCycles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumStormSummaryCycles)
	var cycles int64
	err := row.Scan(&cycles)
	return cycles, err
}
