// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watermarks.sql

package sqlcgen

import (
	"context"
	"time"
)

const getWatermark = `-- name: GetWatermark :one
SELECT inserted_at FROM consumer_watermarks WHERE consumer = $1 AND source = $2
`

type GetWatermarkParams struct {
	Consumer string
	Source   string
}

func (q *Queries) GetWatermark(ctx context.Context, arg GetWatermarkParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getWatermark, arg.Consumer, arg.Source)
	var inserted_at time.Time
	err := row.Scan(&inserted_at)
	return inserted_at, err
}

const lagBoundary = `-- name: LagBoundary :one
SELECT (now() - make_interval(secs => $1::float8))::timestamptz AS boundary
`

// The newest inserted_at a poller may read: now() minus the lag that covers
// in-flight ingest transactions. Computed in SQL so only the DB clock matters.
func (q *Queries) LagBoundary(ctx context.Context, lagSeconds float64) (time.Time, error) {
	row := q.db.QueryRow(ctx, lagBoundary, lagSeconds)
	var boundary time.Time
	err := row.Scan(&boundary)
	return boundary, err
}

const pollAlarmEvents = `-- name: PollAlarmEvents :many
WITH bound AS (
  SELECT max(inserted_at) AS hi FROM (
    SELECT DISTINCT inserted_at FROM alarm_events
    WHERE inserted_at > $1 AND inserted_at <= now() - make_interval(secs => $2::float8)
    ORDER BY inserted_at LIMIT $3
  ) g
)
SELECT a.device_id, a.raised_at, a.f_cnt, a.code, a.value, a.rssi_dbm, a.snr_db, a.sf, a.gateway_id, a.dedup_id, a.inserted_at FROM alarm_events a, bound
WHERE a.inserted_at > $1 AND a.inserted_at <= bound.hi
ORDER BY a.inserted_at, a.device_id, a.raised_at, a.f_cnt
`

type PollAlarmEventsParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

func (q *Queries) PollAlarmEvents(ctx context.Context, arg PollAlarmEventsParams) ([]AlarmEvent, error) {
	rows, err := q.db.Query(ctx, pollAlarmEvents, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlarmEvent{}
	for rows.Next() {
		var i AlarmEvent
		if err := rows.Scan(
			&i.DeviceID,
			&i.RaisedAt,
			&i.FCnt,
			&i.Code,
			&i.Value,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollCycleEvents = `-- name: PollCycleEvents :many

WITH bound AS (
  SELECT max(inserted_at) AS hi FROM (
    SELECT DISTINCT inserted_at FROM cycle_events
    WHERE inserted_at > $1 AND inserted_at <= now() - make_interval(secs => $2::float8)
    ORDER BY inserted_at LIMIT $3
  ) g
)
SELECT c.device_id, c.started_at, c.f_cnt, c.received_at, c.run_s, c.peak_current_a, c.level_start_mm, c.level_end_mm, c.pump_id, c.est_volume_l, c.rssi_dbm, c.snr_db, c.sf, c.gateway_id, c.dedup_id, c.inserted_at FROM cycle_events c, bound
WHERE c.inserted_at > $1 AND c.inserted_at <= bound.hi
ORDER BY c.inserted_at, c.device_id, c.started_at, c.f_cnt
`

type PollCycleEventsParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

// Poll queries: rows newer than the watermark, never splitting an inserted_at
// group (all rows of one ingest batch share it), bounded to max_groups groups
// and to the lag boundary.
func (q *Queries) PollCycleEvents(ctx context.Context, arg PollCycleEventsParams) ([]CycleEvent, error) {
	rows, err := q.db.Query(ctx, pollCycleEvents, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CycleEvent{}
	for rows.Next() {
		var i CycleEvent
		if err := rows.Scan(
			&i.DeviceID,
			&i.StartedAt,
			&i.FCnt,
			&i.ReceivedAt,
			&i.RunS,
			&i.PeakCurrentA,
			&i.LevelStartMm,
			&i.LevelEndMm,
			&i.PumpID,
			&i.EstVolumeL,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollDetections = `-- name: PollDetections :many
WITH bound AS (
  SELECT max(inserted_at) AS hi FROM (
    SELECT DISTINCT inserted_at FROM detections
    WHERE inserted_at > $1 AND inserted_at <= now() - make_interval(secs => $2::float8)
    ORDER BY inserted_at LIMIT $3
  ) g
)
SELECT d.device_id, d.code, d.action, d.observed_at, d.f_cnt, d.detail, d.inserted_at FROM detections d, bound
WHERE d.inserted_at > $1 AND d.inserted_at <= bound.hi
ORDER BY d.inserted_at, d.device_id, d.observed_at, d.f_cnt
`

type PollDetectionsParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

func (q *Queries) PollDetections(ctx context.Context, arg PollDetectionsParams) ([]Detection, error) {
	rows, err := q.db.Query(ctx, pollDetections, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Detection{}
	for rows.Next() {
		var i Detection
		if err := rows.Scan(
			&i.DeviceID,
			&i.Code,
			&i.Action,
			&i.ObservedAt,
			&i.FCnt,
			&i.Detail,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollReadings = `-- name: PollReadings :many
WITH bound AS (
  SELECT max(inserted_at) AS hi FROM (
    SELECT DISTINCT inserted_at FROM readings
    WHERE inserted_at > $1 AND inserted_at <= now() - make_interval(secs => $2::float8)
    ORDER BY inserted_at LIMIT $3
  ) g
)
SELECT r.device_id, r.ts, r.f_cnt, r.level_mm, r.temp_c, r.rh_pct, r.batt_mv, r.cycles_since_last, r.mains_ok, r.float_high, r.backup_ran, r.sensor_fault, r.rssi_dbm, r.snr_db, r.sf, r.gateway_id, r.dedup_id, r.inserted_at FROM readings r, bound
WHERE r.inserted_at > $1 AND r.inserted_at <= bound.hi
ORDER BY r.inserted_at, r.device_id, r.ts, r.f_cnt
`

type PollReadingsParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

func (q *Queries) PollReadings(ctx context.Context, arg PollReadingsParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, pollReadings, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reading{}
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.DeviceID,
			&i.Ts,
			&i.FCnt,
			&i.LevelMm,
			&i.TempC,
			&i.RhPct,
			&i.BattMv,
			&i.CyclesSinceLast,
			&i.MainsOk,
			&i.FloatHigh,
			&i.BackupRan,
			&i.SensorFault,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWatermark = `-- name: SetWatermark :exec
INSERT INTO consumer_watermarks (consumer, source, inserted_at)
VALUES ($1, $2, $3)
ON CONFLICT (consumer, source) DO UPDATE
  SET inserted_at = EXCLUDED.inserted_at, updated_at = now()
`

type SetWatermarkParams struct {
	Consumer   string
	Source     string
	InsertedAt time.Time
}

func (q *Queries) SetWatermark(ctx context.Context, arg SetWatermarkParams) error {
	_, err := q.db.Exec(ctx, setWatermark, arg.Consumer, arg.Source, arg.InsertedAt)
	return err
}
