// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteRainfallExcept = `-- name: DeleteRainfallExcept :execrows
DELETE FROM rainfall
WHERE source = $1 AND station_id = $2
  AND ts >= $3 AND ts < $4
  AND NOT (ts = ANY($5::timestamptz[]))
`

type DeleteRainfallExceptParams struct {
	Source    string
	StationID string
	FromTs    time.Time
	ToTs      time.Time
	Keep      []time.Time
}

// Removes a station's rows in [from_ts, to_ts) that a re-derivation no longer produces.
func (q *Queries) DeleteRainfallExcept(ctx context.Context, arg DeleteRainfallExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRainfallExcept,
		arg.Source,
		arg.StationID,
		arg.FromTs,
		arg.ToTs,
		arg.Keep,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRainGaugeUplinks = `-- name: ListRainGaugeUplinks :many
SELECT device_id, ts, f_cnt, tip_count, mm_per_tip, interval_s, batt_mv, counter_reset, sensor_fault, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM rain_gauge_uplinks
WHERE device_id = $1 AND ts >= $2 AND ts <= $3
ORDER BY ts, f_cnt
`

type ListRainGaugeUplinksParams struct {
	DeviceID string
	FromTs   time.Time
	ToTs     time.Time
}

func (q *Queries) ListRainGaugeUplinks(ctx context.Context, arg ListRainGaugeUplinksParams) ([]RainGaugeUplink, error) {
	rows, err := q.db.Query(ctx, listRainGaugeUplinks, arg.DeviceID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RainGaugeUplink{}
	for rows.Next() {
		var i RainGaugeUplink
		if err := rows.Scan(
			&i.DeviceID,
			&i.Ts,
			&i.FCnt,
			&i.TipCount,
			&i.MmPerTip,
			&i.IntervalS,
			&i.BattMv,
			&i.CounterReset,
			&i.SensorFault,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRainfall = `-- name: ListRainfall :many
SELECT source, station_id, ts, interval_s, mm FROM rainfall
WHERE ts >= $1 AND ts < $2
  AND ts + make_interval(secs => interval_s) > $3
ORDER BY source, station_id, ts
`

type ListRainfallParams struct {
	ScanFrom time.Time
	ToTs     time.Time
	FromTs   time.Time
}

type ListRainfallRow struct {
	Source    string
	StationID string
	Ts        time.Time
	IntervalS int32
	Mm        float64
}

// Intervals overlapping [from_ts, to_ts); scan_from bounds the index scan
// (no interval is longer than from_ts - scan_from).
func (q *Queries) ListRainfall(ctx context.Context, arg ListRainfallParams) ([]ListRainfallRow, error) {
	rows, err := q.db.Query(ctx, listRainfall, arg.ScanFrom, arg.ToTs, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRainfallRow{}
	for rows.Next() {
		var i ListRainfallRow
		if err := rows.Scan(
			&i.Source,
			&i.StationID,
			&i.Ts,
			&i.IntervalS,
			&i.Mm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollRainGaugeUplinks = `-- name: PollRainGaugeUplinks :many

WITH bound AS (
  SELECT max(inserted_at) AS hi FROM (
    SELECT DISTINCT inserted_at FROM rain_gauge_uplinks
    WHERE inserted_at > $1 AND inserted_at <= now() - make_interval(secs => $2::float8)
    ORDER BY inserted_at LIMIT $3
  ) g
)
SELECT u.device_id, u.ts, u.f_cnt, u.tip_count, u.mm_per_tip, u.interval_s, u.batt_mv, u.counter_reset, u.sensor_fault, u.rssi_dbm, u.snr_db, u.sf, u.gateway_id, u.dedup_id, u.inserted_at FROM rain_gauge_uplinks u, bound
WHERE u.inserted_at > $1 AND u.inserted_at <= bound.hi
ORDER BY u.inserted_at, u.device_id, u.ts, u.f_cnt
`

type PollRainGaugeUplinksParams struct {
	After      time.Time
	LagSeconds float64
	MaxGroups  int32
}

// Phase 4 weather service: rain-gauge uplinks → rainfall, ECCC rainfall, and
// rainfall reads for storm-analytics and the alerts outage-risk rule.
func (q *Queries) PollRainGaugeUplinks(ctx context.Context, arg PollRainGaugeUplinksParams) ([]RainGaugeUplink, error) {
	rows, err := q.db.Query(ctx, pollRainGaugeUplinks, arg.After, arg.LagSeconds, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RainGaugeUplink{}
	for rows.Next() {
		var i RainGaugeUplink
		if err := rows.Scan(
			&i.DeviceID,
			&i.Ts,
			&i.FCnt,
			&i.TipCount,
			&i.MmPerTip,
			&i.IntervalS,
			&i.BattMv,
			&i.CounterReset,
			&i.SensorFault,
			&i.RssiDbm,
			&i.SnrDb,
			&i.Sf,
			&i.GatewayID,
			&i.DedupID,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rainGaugeUplinkAfter = `-- name: RainGaugeUplinkAfter :one
SELECT device_id, ts, f_cnt, tip_count, mm_per_tip, interval_s, batt_mv, counter_reset, sensor_fault, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM rain_gauge_uplinks
WHERE device_id = $1 AND ts > $2
ORDER BY ts, f_cnt
LIMIT 1
`

type RainGaugeUplinkAfterParams struct {
	DeviceID string
	Ts       time.Time
}

func (q *Queries) RainGaugeUplinkAfter(ctx context.Context, arg RainGaugeUplinkAfterParams) (RainGaugeUplink, error) {
	row := q.db.QueryRow(ctx, rainGaugeUplinkAfter, arg.DeviceID, arg.Ts)
	var i RainGaugeUplink
	err := row.Scan(
		&i.DeviceID,
		&i.Ts,
		&i.FCnt,
		&i.TipCount,
		&i.MmPerTip,
		&i.IntervalS,
		&i.BattMv,
		&i.CounterReset,
		&i.SensorFault,
		&i.RssiDbm,
		&i.SnrDb,
		&i.Sf,
		&i.GatewayID,
		&i.DedupID,
		&i.InsertedAt,
	)
	return i, err
}

const rainGaugeUplinkBefore = `-- name: RainGaugeUplinkBefore :one
SELECT device_id, ts, f_cnt, tip_count, mm_per_tip, interval_s, batt_mv, counter_reset, sensor_fault, rssi_dbm, snr_db, sf, gateway_id, dedup_id, inserted_at FROM rain_gauge_uplinks
WHERE device_id = $1 AND ts < $2
ORDER BY ts DESC, f_cnt DESC
LIMIT 1
`

type RainGaugeUplinkBeforeParams struct {
	DeviceID string
	Ts       time.Time
}

func (q *Queries) RainGaugeUplinkBefore(ctx context.Context, arg RainGaugeUplinkBeforeParams) (RainGaugeUplink, error) {
	row := q.db.QueryRow(ctx, rainGaugeUplinkBefore, arg.DeviceID, arg.Ts)
	var i RainGaugeUplink
	err := row.Scan(
		&i.DeviceID,
		&i.Ts,
		&i.FCnt,
		&i.TipCount,
		&i.MmPerTip,
		&i.IntervalS,
		&i.BattMv,
		&i.CounterReset,
		&i.SensorFault,
		&i.RssiDbm,
		&i.SnrDb,
		&i.Sf,
		&i.GatewayID,
		&i.DedupID,
		&i.InsertedAt,
	)
	return i, err
}

const rainNear = `-- name: RainNear :one
SELECT
  coalesce(sum(mm) FILTER (WHERE ts + make_interval(secs => interval_s) > $1), 0)::float8 AS mm,
  coalesce(max(ts + make_interval(secs => interval_s)), 'epoch'::timestamptz)::timestamptz AS covered_until
FROM rainfall
WHERE ts >= $2 AND ts < $3
`

type RainNearParams struct {
	FromTs   time.Time
	ScanFrom time.Time
	ToTs     time.Time
}

type RainNearRow struct {
	Mm           float64
	CoveredUntil time.Time
}

// Rain recorded by any source in intervals overlapping [from_ts, to_ts), and
// how far the data reach before to_ts (the outage-risk rain term).
func (q *Queries) RainNear(ctx context.Context, arg RainNearParams) (RainNearRow, error) {
	row := q.db.QueryRow(ctx, rainNear, arg.FromTs, arg.ScanFrom, arg.ToTs)
	var i RainNearRow
	err := row.Scan(&i.Mm, &i.CoveredUntil)
	return i, err
}

const rainfallCoveredUntil = `-- name: RainfallCoveredUntil :one
SELECT coalesce(max(ts + make_interval(secs => interval_s)), 'epoch'::timestamptz)::timestamptz AS covered_until
FROM rainfall
WHERE source = $1 AND ts >= $2
`

type RainfallCoveredUntilParams struct {
	Source   string
	ScanFrom time.Time
}

// End of the newest interval of a source: how far its data reach.
func (q *Queries) RainfallCoveredUntil(ctx context.Context, arg RainfallCoveredUntilParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, rainfallCoveredUntil, arg.Source, arg.ScanFrom)
	var covered_until time.Time
	err := row.Scan(&covered_until)
	return covered_until, err
}

const upsertRainfall = `-- name: UpsertRainfall :execrows
INSERT INTO rainfall (source, station_id, ts, interval_s, mm)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source, station_id, ts) DO UPDATE
  SET interval_s = EXCLUDED.interval_s, mm = EXCLUDED.mm, updated_at = now()
  WHERE rainfall.interval_s IS DISTINCT FROM EXCLUDED.interval_s
     OR rainfall.mm IS DISTINCT FROM EXCLUDED.mm
`

type UpsertRainfallParams struct {
	Source    string
	StationID string
	Ts        time.Time
	IntervalS int32
	Mm        float64
}

// Only an insert or a real change bumps updated_at, which storm-analytics polls.
func (q *Queries) UpsertRainfall(ctx context.Context, arg UpsertRainfallParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRainfall,
		arg.Source,
		arg.StationID,
		arg.Ts,
		arg.IntervalS,
		arg.Mm,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
